### ISSUE TITLE
I ran into this error while trying to run the provided sample app

### ISSUE THREAD

**Issue by skripsimu** [infobip/mobile-messaging-flutter-plugin#1]
Can you tell me where is my mistake?

<img width="1203" alt="Screen Shot 2021-09-03 at 12 58 29" src="https://user-images.githubusercontent.com/35763779/131957716-c0eceebf-deec-40fc-925c-03b8a6e21651.png">

**Comment by kostap13** [comment]
Hi @skripsimu 
Fixed. You can try it now

**Comment by kostap13** [comment]
btw, you should use version: 0.0.2
```yaml
dependencies:
    infobip_mobilemessaging: '^0.0.2'
```
