### ISSUE TITLE
No connection message when I start Infobip mobile messaging chat "Flutter integration"

### ISSUE THREAD

**Issue by AsmaaMagdHelali** [infobip/mobile-messaging-flutter-plugin#11]
Hi, 
I am trying to integrate "infobip_mobilemessaging: ^0.9.1" in my flutter app but it shows "**No connection**" message and edit text is also disable 

#Flutter
#infobip_mobilemessaging
------------
await InfobipMobilemessaging.init(Configuration(
          applicationCode:"APPLICATION-CODE",
          androidSettings: AndroidSettings(),
          inAppChatEnabled: true,
          iosSettings: IOSSettings(
              notificationTypes: ["alert", "badge", "sound"],
              forceCleanup: false,
              logging: true)));
  InfobipMobilemessaging.setupiOSChatSettings(IOSChatSettings(
    title: 'Flutter Chat',
    sendButtonColor: '#ff5722',
    navigationBarItemsColor: '#ff8a50',
    navigationBarColor: '#4DBB7E',
    navigationBarTitleColor: '#ffffff',
  ));

![Screenshot 2023-03-20 at 12 31 02 PM](https://user-images.githubusercontent.com/118978918/226314441-b9ea6efc-5d5f-432a-8b9c-3957f179e796.png)

**Comment by fortesdev** [comment]
Hi,
"No connection" is a general error most probably indicating that the setup is incorrect. You can enable debug logs to see the messages in Xcode console for more details. 
InAppChat needs a "widgetId" and a "PushRegistrationId" - an error when retrieving those values will indicate that some step in your setup is missing or wrong. We suggest you recheck the instructions here:

https://www.infobip.com/docs/mobile-app-messaging/getting-started
and
https://www.infobip.com/docs/live-chat/getting-started

**Comment by AsmaaMagdHelali** [comment]
Do you know where can I put "widgetId" and a "PushRegistrationId" in AppChat configuration code; there isn't any documentation for that ?

**Comment by fortesdev** [comment]
There is no need for you to set those ids, they are requested by the SDK on run time. But you will read in the console, if debug logs are enabled:
a) that those values are coming - your setup on Infobip's portal and your app are correct, and inAppChat can then work.
b) or an error is returned - meaning your setup on Infobip's portal and/or your app are incorrect, and the "no connection" message will be prompted.

Please, re-recheck your setup (push notifications must be enabled in capabilities, correct iOS certificates needs to exist in the mobile app profile, livechat widget must be pointing to the same mobile app profile, etc.)

**Comment by fortesdev** [comment]
1- You can test it in the free version. For production volumes and pricing please contact us here https://www.infobip.com/contact
2- Search "Link the mobile application profile to the widget configuration" in one of the links I provided:
https://www.infobip.com/docs/live-chat/getting-started

**Comment by AsmaaMagdHelali** [comment]
Thank you for your help
