### ISSUE TITLE
Init iOS without registering

### ISSUE THREAD

**Issue by TonyLopesCellenza** [infobip/mobile-messaging-flutter-plugin#12]
Hi,

I've notice in the flutter pluggin we can't init the sdk on the iOS platform without displaying the notification permission popup.
This "option" is available in the iOS native SDK with the `withoutRegisteringForRemoteNotifications` and `didRegisterForRemoteNotificationsWithDeviceToken` methods but don't find it in this flutter plugin (except if I missed it 😅).

So I would like to know if we could have the same feature in the flutter plugin, for example adding a new property in the `IOSSettings` object to enable or not the registration and a method to register the token ?

Thanks.

**Comment by TonyLopesCellenza** [comment]
> Hello there,
> 
> Indeed, this option is currently not available in Flutter plugin, we will add in the next release.

Do you have any idea/date when you will be able to deliver the next release ? 😁

**Comment by alboldy-ib** [comment]
It will be taken into the next sprint, so should be done by the next week's end.

**Comment by alboldy-ib** [comment]
Hi @TonyLopesCellenza ,
Feel free to check the [0.9.3 release](https://github.com/infobip/mobile-messaging-flutter-plugin/releases/tag/0.9.3), you may find implementation in [example application](https://github.com/infobip/mobile-messaging-flutter-plugin/blob/main/example/lib/main.dart#L83) - set the parameter to true, and register for notifications when necessary by calling `InfobipMobilemessaging.registerForRemoteNotifications();`

**Comment by TonyLopesCellenza** [comment]
Hi, thank you for your responsiveness.

I perform a quick test and it seems good 👍🏻
