### ISSUE TITLE
App crashes after a hot restart

### ISSUE THREAD

**Issue by ViacheslavBER** [infobip/mobile-messaging-flutter-plugin#13]
Flutter app crashes with this logs

MobileMessaging/MobileMessaging.swift:750: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
Lost connection to device.
Exception: Unable to terminate org.infobip.plugins.mobilemessaging.flutter on 8BFB3396-CF74-4A23-B39E-5CF4256595BC:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
  Command: /usr/bin/arch -arm64e xcrun simctl terminate 8BFB3396-CF74-4A23-B39E-5CF4256595BC org.infobip.plugins.mobilemessaging.flutter

**Comment by riskpp** [comment]
Hello @ViacheslavBER, could you please provide more information, version of the Mobile Messaging plugin used, what are the steps to reproduce this issue? Are you able to reproduce it using [example application](https://github.com/infobip/mobile-messaging-flutter-plugin/wiki/How-to-start-Example-app)?

Thank you!

**Comment by ViacheslavBER** [comment]
Hello @riskpp, thanks for your response,  our app use 0.9.3 version of Infobip, it works, so i think set up is correct. 

for reproduce there are the steps: 

1. run the app
2. wait a second or more
3. click Flutter Hot Restart (not Hot Reload) 

We saw that this problem appeared after adding Infobip, so I also tested it on your example app (with our credentials) and it also had the same problem, 

PS we use 3 method of [setup](wehttps://github.com/infobip/mobile-messaging-flutter-plugin/wiki/Applying-Firebase-configuration-in-MobileMessaging-Flutter-plugin#option3)

**Comment by alboldy-ib** [comment]
Hello @ViacheslavBER ,

A fix version had been released - [1.1.2](https://github.com/infobip/mobile-messaging-flutter-plugin/releases/tag/1.1.2) - feel free to check it.

**Comment by ViacheslavBER** [comment]
thank !

**Comment by riskpp** [comment]
closing, issue is fixed
