### ISSUE TITLE
Is there any return value to check if the notifications are enabled or disabled 

### ISSUE THREAD

**Issue by Suheb786** [infobip/mobile-messaging-flutter-plugin#14]
Is there any return value to check if the app notifications are enabled or disabled ?

**Comment by alboldy-ib** [comment]
Hello there,
Yes, you can by getting installation and checking `isPushRegistrationEnabled` value:

```
var installation = await InfobipMobilemessaging.getInstallation();
if (installation.isPushRegistrationEnabled) 
    // do something
```

**Comment by riskpp** [comment]
I'll close the issue because no new comments appeared for more than 2 weeks.
