### ISSUE TITLE
Does Infobip flutter plugin support Huawei devices without google play services?

### ISSUE THREAD

**Issue by Ikami-Mercy** [infobip/mobile-messaging-flutter-plugin#16]
Hi there, 
I recently integrated infobip into my Flutter app, and it works flawlessly on iOS and Android devices except for Huawei devices that lack Google Play services.
I have configured HMS in the app as per your Huawei set up [documentation](https://github.com/infobip/mobile-messaging-sdk-huawei?tab=readme-ov-file#mobile-messaging-sdk-for-huawei-on-android) but my app is still experiencing this error:
```
W/MobileMessaging(14392): Registration is not available yet
W/MobileMessaging(14392): Registration not available yet, you can fetch installation when push registration ID becomes available
E/flutter (14392): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(20006, There is no valid registration, SDK_ERROR, 20006, There is no valid registration, null)
```
The` await InfobipMobilemessaging.init` method is throwing this error:
```
Cannot start SDK: SDK_ERROR, 20001, Error accessing play services, use provided 'googleErrorCode' with 'GoogleApiAvailability.getErrorDialog()' (https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html) errorCode: 9
E/MethodChannel#infobip_mobilemessaging( 9161): Failed to handle method call
E/MethodChannel#infobip_mobilemessaging( 9161): java.lang.IllegalArgumentException: Unsupported value: 'ERROR_ACCESSING_PLAY_SERVICES' of type 'class org.infobip.mobile.messaging.mobileapi.InternalSdkError'
```
Please assist.

**Comment by alboldy-ib** [comment]
Hello there,
Yes, currently our Flutter plugin does not support Huawei, only Android devices.

**Comment by Ikami-Mercy** [comment]
Hi @alboldy-ib , 
I am seeking your assistance regarding an issue I encountered while integrating a Huawei InfobipPlugin into my Flutter app as a workaround for the above error. This integration is crucial as my app needs to support Huawei devices that lack Google Play services.

However, after creating the Huawei InfobipPlugin, I am now experiencing the following error:

```
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
Duplicate class org.infobip.mobile.messaging.ApplicationCodeProvider found in modules jetified-infobip-mobile-messaging-android-sdk-12.4.0-runtime (com.infobip:infobip-mobile-messaging-android-sdk:12.4.0) and jetified-infobip-mobile-messaging-huawei-sdk-6.3.0-runtime (com.infobip:infobip-mobile-messaging-huawei-sdk:6.3.0).
```
I attempted to exclude the duplicate module with the following configuration:

`exclude group: 'com.infobip', module: 'infobip-mobile-messaging-huawei-sdk'
`
Could you provide insights or advice on how to resolve this duplicate class issue? Any guidance on how to successfully integrate the Huawei Infobip plugin into our Flutter app would be greatly appreciated.

Thank you

**Comment by alboldy-ib** [comment]
Hello,

As previously mentioned, we do not yet support Huawei on Flutter plugin. 
I could only suggest to look at [our Cordova plugin](https://github.com/infobip/mobile-messaging-cordova-plugin) implementation - it requires not only inclusion of proper SDKs, but also some code changes in plugin's code (for example, everything Firebase-related should not be present on Android part, also might be some dependency clashes). 

I can suggest you contacting your designated account manager and forwarding this feature request.

**Comment by Ikami-Mercy** [comment]
Hello,

I am trying to display push notifications on iOS while my app is in the
foreground. I added *fullFeaturedInAppsEnabled: true* to my Configuration
object, but the notifications are still not appearing. Could you please
provide guidance on how to achieve this.


This is my AppDelegate.swift code:

import UIKit
import Flutter
import MobileMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions:
[UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as?
UNUserNotificationCenterDelegate
    }

    MobileMessagingPluginApplicationDelegate.install()
    GeneratedPluginRegistrant.register(with: self)

    return super.application(application,
didFinishLaunchingWithOptions: launchOptions)
  }

  override func application(_ application: UIApplication,
didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    MobileMessaging.didRegisterForRemoteNotificationsWithDeviceToken(deviceToken)
  }

  override func application(_ application: UIApplication,
didReceiveRemoteNotification userInfo: [AnyHashable : Any],
fetchCompletionHandler completionHandler: @escaping
(UIBackgroundFetchResult) -> Void) {
    MobileMessaging.didReceiveRemoteNotification(userInfo,
fetchCompletionHandler: completionHandler)
  }

   // Handle notifications in the foreground
   @available(iOS 10.0, *)
   override func userNotificationCenter(_ center:
UNUserNotificationCenter,willPresent notification:
UNNotification,withCompletionHandler completionHandler: @escaping
(UNNotificationPresentationOptions) -> Void) {
      completionHandler([.alert, .sound, .badge,])
    }
}

**Comment by riskpp** [comment]
Hello, it seems it may be closed, feel free to open another one if you disagree or have other questions.

**Comment by dhiyaaulauliyaa** [comment]
hi @Ikami-Mercy did you manage to make it work on huawei device?
