### ISSUE TITLE
App force closed the after init called

### ISSUE THREAD

**Issue by skripsimu** [infobip/mobile-messaging-flutter-plugin#3]
My app force closed after InfobipMobilemessaging.init called, and I attached the error log below

`MobileMessagingFlutter( 8712): onMethodCall
I/MobileMessagingFlutter( 8712): activity: id.danafix.mobile.MainActivity@27af77c
D/MobileMessagingFlutter( 8712): init
D/CompatibilityChangeReporter( 8712): Compat change id reported: 147600208; UID 10898; state: ENABLED
V/MobileMessaging( 8712): BASE URL >>>
W/MobileMessaging( 8712): Registration not available yet, will report user session later
2
W/MobileMessaging( 8712): Registration is not available yet
W/MobileMessaging( 8712): Registration not available yet, will patch messages later
D/MMHTTP  ( 8712): REQUEST: Request(httpMethod=GET, uri=https://mobile.infobip.com/mobile/1/baseurl, apiKey='API_KEY', credentials=null, headers={applicationcode=[31f8745ad6], pushregistrationid=[null], foreground=[true], installationid=[8801dabf-86a7-4bda-8c43-f00c33122948]}, queryParams={}, body=null)
E/AndroidRuntime( 8712): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 8712): Process: id.danafix.mobile, PID: 8712
E/AndroidRuntime( 8712): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 8712): 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime( 8712): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 8712): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 8712): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 8712): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8712): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8712): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 8712): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.cloud.firebase.FirebaseRegistrationTokenHandler.acquireNewToken(FirebaseRegistrationTokenHandler.java:57)
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.cloud.MobileMessagingCloudHandler.handleTokenAcquire(MobileMessagingCloudHandler.java:74)
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.cloud.MobileMessagingCloudHandler.handleWork(MobileMessagingCloudHandler.java:61)
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.cloud.MobileMessagingCloudService.onHandleWork(MobileMessagingCloudService.java:119)
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.platform.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:415)
E/AndroidRuntime( 8712): 	at org.infobip.mobile.messaging.platform.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:405)
E/AndroidRuntime( 8712): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime( 8712): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 8712): 	... 3 more
E/AndroidRuntime( 8712): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~_eKmfHmzQPGer9EqQMHUlw==/id.danafix.mobile-b2QOqLfi2Pr_zQ669BDogg==/base.apk"],nativeLibraryDirectories=[/data/app/~~_eKmfHmzQPGer9EqQMHUlw==/id.danafix.mobile-b2QOqLfi2Pr_zQ669BDogg==/lib/arm64, /data/app/~~_eKmfHmzQPGer9EqQMHUlw==/id.danafix.mobile-b2QOqLfi2Pr_zQ669BDogg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 8712): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 8712): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8712): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8712): 	... 11 more
D/TransportRuntime.SQLiteEventStore( 8712): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler( 8712): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=761016454 in 1000ms(Backend next call timestamp 0). Attempt 1
I/Process ( 8712): Sending signal. PID: 8712 SIG: 9
Lost connection to device.
Exited (sigterm)

`

**Comment by kostap13** [comment]
Hi @skripsimu 
Could you please provide a little bit more details?
1. plugin version
2. OS (Android, iOS) and it's version

Thank you

**Comment by skripsimu** [comment]
I use 0.4.1 plugin version, and run on Android 11

**Comment by kostap13** [comment]
Try to add:

1.` [App path]/android/app/src/main/res/values/strings.xml`
Note that for provided sample project, path will be smth like: `/Users/..../infobip-mobile-messaging-flutter-plugin/example/android/app/src/main/res/values/strings.xml`
2. Content:
```
<resources>
    <string name="google_app_id">Your Firebase Sender ID</string>
    <string name="infobip_application_code">Your Application Code</string>
    <string name="ib_chat_view_title">Chat Name</string>
</resources>
```

**Comment by kostap13** [comment]
Here the sample:
https://github.com/infobip/mobile-messaging-flutter-plugin/blob/main/example/android/app/src/main/res/values/strings.xml

**Comment by skripsimu** [comment]
I've added **_strings.xml_** but got new error duplicate resource **_google_app_id_**

`ERROR:[string/google_app_id] /Users/Project/build/app/generated/res/google-services/debug/values/values.xml [string/google_app_id] /Users/Project/android/app/src/main/res/values/strings.xml: Resource and asset merger: Duplicate resources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /Users/Project/build/app/generated/res/google-services/debug/values/values.xml	[string/google_app_id] /Users/Project/android/app/src/main/res/values/strings.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by skripsimu** [comment]
this is the auto-generated values.xml from google-services.json which reads duplicated with strings.xml

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_web_client_id" translatable="false"></string>
    <string name="gcm_defaultSenderId" translatable="false"></string>
    <string name="google_api_key" translatable="false"></string>
    <string name="google_app_id" translatable="false"></string>
    <string name="google_crash_reporting_api_key" translatable="false"></string>
    <string name="google_storage_bucket" translatable="false"></string>
    <string name="project_id" translatable="false"></string>
</resources>
`

**Comment by kostap13** [comment]
Hi @skripsimu 
Does google-services.json required to yours project?

**Comment by skripsimu** [comment]
Yes it's required, because I'm using some plugins from firebase

**Comment by kostap13** [comment]
Ok, thank you
I'll provide fix ASAP

**Comment by riskpp** [comment]
@skripsimu Could you please share which plugins and versions you are using from firebase? It'll help us to reproduce the issue.
BR, Olga

**Comment by skripsimu** [comment]
Hi @riskpp here's the plugin and version I'm using from firebase

  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.2.4
  firebase_performance: ^0.7.1+4

**Comment by kostap13** [comment]
@skripsimu 
btw, do you have firebase_core dependency? If yes - what version?

**Comment by skripsimu** [comment]
no, I don't have it in the project

**Comment by kostap13** [comment]
Hi @skripsimu 

Here you can see PR with changes what fixes this issue:
https://github.com/infobip/mobile-messaging-flutter-plugin/pull/4/files

All changes are done at example application. So, you can use it like a sample to make changes at yours project.

Also, we provided new version of flutter-plugin: 0.4.2. It's not required to use it right now, fix can be done without updating. But 0.4.2 maybe useful if you'll see conflicts while updating firebase's plugins dependencies. 

Note that, provided firebase_* dependencies have conflicts for some versions. For example, you can see this issue at firebase:
https://github.com/firebase/firebase-android-sdk/issues/1662


If you'll have any others questions, feel free to ask.


Best regards

**Comment by kostap13** [comment]
@skripsimu 
Shortly, the main idea for fixing this issue is to add `apply plugin: 'com.google.gms.google-services' `:
https://github.com/infobip/mobile-messaging-flutter-plugin/pull/4/files#diff-39ab2ed24002fb8e39b9db8ebac35907f77395dbc3c2faf95e6e6b6805e0b9ceR59

All other code related to adding other firebase dependencies
