### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MoEPluginBase"

### ISSUE THREAD

**Issue by akshay-kapase** [infobip/mobile-messaging-flutter-plugin#7]
Facing issues when trying to build the project in Xcode

**Comment by akshay-kapase** [comment]
[!] CocoaPods could not find compatible versions for pod "MoEPluginBase":
  In Podfile:
    moengage_flutter (from `.symlinks/plugins/moengage_flutter/ios`) was resolved to 4.1.0, which depends on
      MoEPluginBase (~> 2.1.0)

    moengage_inbox (from `.symlinks/plugins/moengage_inbox/ios`) was resolved to 3.2.0, which depends on
      MoEPluginBase (~> 2.3.0)

**Comment by riskpp** [comment]
Hi @akshay-kapase, we don't have this plugin as a dependency, may be better to check this plugin/Pod issues.

**Comment by riskpp** [comment]
Closing the issue, because it isn't  connected with the plugin and doesn't have activity for a long time.
