### ISSUE TITLE
[!] Unable to find a target named `MobileMessagingNotificationExtension` in project `Runner.xcodeproj`, did find `Runner`.

### ISSUE THREAD

**Issue by akshay-kapase** [infobip/mobile-messaging-flutter-plugin#8]
Facing this issue when called "pod update" in the terminal

[!] Unable to find a target named `MobileMessagingNotificationExtension` in project `Runner.xcodeproj`, did find `Runner`.

**Comment by riskpp** [comment]
Hi @akshay-kapase, have you integrated [NotificationExtension](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10)? You should have additional target in your project called `MobileMessagingNotificationExtension` after integration.

**Comment by akshay-kapase** [comment]
How to integrate NotificationExtension ?

**Comment by riskpp** [comment]
You can find instructions by the provided link - https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10

**Comment by riskpp** [comment]
How your Podfile looks like? Could you please provide the code?

**Comment by akshay-kapase** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'MobileMessaging'

      target 'MobileMessagingNotificationExtension' do
          inherit! :search_paths
      end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 arm64"
    end
  end
end

**Comment by riskpp** [comment]
Hi @akshay-kapase, I've updated a bit [Quick Start guide](https://github.com/infobip/mobile-messaging-flutter-plugin#quick-start-guide), please check that you configured iOS platform exact as written there. As I can see in your podfile you are missing couple of things:
1. You need to uncomment line `# platform :ios, '9.0'` and change platform to the 12.0 as written in Quick start guide
2. You don't need to add manually `pod 'MobileMessaging'`, it should be added automatically by flutter after you add the mobile messaging plugin as a dependency in your `pubspec.yaml`
3. Not sure have you added MobileMessagingNotificationExtension, the step for adding right now added to Quick start guide and link for instructions - https://github.com/infobip/mobile-messaging-flutter-plugin/wiki/Delivery-improvements-and-rich-content-notifications

**Comment by riskpp** [comment]
Hi @akshay-kapase, I'll close the issue, you can reopen it if problem isn't resolved.
