### ISSUE TITLE
FirebaseOptions isn't a function

### ISSUE THREAD

**Issue by sndpsdhsvm** [infobip/mobile-messaging-flutter-plugin#9]
<img width="966" alt="Screenshot 2022-09-12 at 11 37 40 AM" src="https://user-images.githubusercontent.com/85545319/189585636-4e28c8dd-796b-480f-9ac4-ac543fa37d33.png">
infobip_mobilemessaging plugin version : 0.7.0 
I'm checking on Android and IOS version

**Comment by riskpp** [comment]
Hi @sndpsdhsvm  thank you for reporting it, it actually means that another dependency (firebase_core) also contains the same name `FirebaseOptions`. We'll check what we can do, may be will rename it. I'll update you here.

**Comment by riskpp** [comment]
@sndpsdhsvm  you can check example right now, I did [small change](https://github.com/infobip/mobile-messaging-flutter-plugin/commit/c3221d751231a6625215ce5063438f63a0676c88) here to make it possible to have 2 defined FirebaseOptions, now it should be fine

**Comment by sndpsdhsvm** [comment]
Thank You

**Comment by davor-komusanac** [comment]
Hi @sndpsdhsvm, just to let you know we have updated integration with Firebase and this is no longer the only way of doing it. We have it added in our w[iki page.](https://github.com/infobip/mobile-messaging-flutter-plugin/wiki/Applying-Firebase-configuration-in-MobileMessaging-Flutter-plugin)
